[project]
name = "django-live"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-extensions>=4.1",
    "django-summernote>=0.8.20.0",
    "ipython>=9.9.0",
    "pillow>=12.1.0",
]
